-- Add user settings columns to users table
ALTER TABLE users
ADD COLUMN IF NOT EXISTS email_notifications BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS promo_notifications BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS public_profile BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS hide_purchase_history BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
ADD COLUMN IF NOT EXISTS bio TEXT;
